package br.com.goinf.entities;
// Generated 13 de jan de 2019 21:10:01 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {

	private int id;
	private String street;
	private String complement;
	private String city;
	private String state;
	private String country;
	private Integer zipcode;
	private Set<Supplier> suppliers = new HashSet<Supplier>(0);

	public Address() {
	}

	public Address(int id) {
		this.id = id;
	}

	public Address(int id, String street, String complement, String city, String state, String country, Integer zipcode,
			Set<Supplier> suppliers) {
		this.id = id;
		this.street = street;
		this.complement = complement;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipcode = zipcode;
		this.suppliers = suppliers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "street", length = 100)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "complement", length = 100)
	public String getComplement() {
		return this.complement;
	}

	public void setComplement(String complement) {
		this.complement = complement;
	}

	@Column(name = "city", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "zipcode")
	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "supplier_has_address", schema = "public", joinColumns = {
			@JoinColumn(name = "address_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "supplier_id", nullable = false, updatable = false) })
	public Set<Supplier> getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}

}
