package br.com.goinf.entities;
// Generated 13 de jan de 2019 21:10:01 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Bankdata generated by hbm2java
 */
@Entity
@Table(name = "bankdata", schema = "public")
public class Bankdata implements java.io.Serializable {

	private int id;
	private String bank;
	private Integer agency;
	private Integer account;
	private Integer agencydigit;
	private Integer accountdigit;
	private Set<Supplier> suppliers = new HashSet<Supplier>(0);

	public Bankdata() {
	}

	public Bankdata(int id) {
		this.id = id;
	}

	public Bankdata(int id, String bank, Integer agency, Integer account, Integer agencydigit, Integer accountdigit,
			Set<Supplier> suppliers) {
		this.id = id;
		this.bank = bank;
		this.agency = agency;
		this.account = account;
		this.agencydigit = agencydigit;
		this.accountdigit = accountdigit;
		this.suppliers = suppliers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bank", length = 100)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "agency")
	public Integer getAgency() {
		return this.agency;
	}

	public void setAgency(Integer agency) {
		this.agency = agency;
	}

	@Column(name = "account")
	public Integer getAccount() {
		return this.account;
	}

	public void setAccount(Integer account) {
		this.account = account;
	}

	@Column(name = "agencydigit")
	public Integer getAgencydigit() {
		return this.agencydigit;
	}

	public void setAgencydigit(Integer agencydigit) {
		this.agencydigit = agencydigit;
	}

	@Column(name = "accountdigit")
	public Integer getAccountdigit() {
		return this.accountdigit;
	}

	public void setAccountdigit(Integer accountdigit) {
		this.accountdigit = accountdigit;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "supplier_has_bankdata", schema = "public", joinColumns = {
			@JoinColumn(name = "bankdata_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "supplier_id", nullable = false, updatable = false) })
	public Set<Supplier> getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}

}
