package br.com.goinf.entities;
// Generated 13 de jan de 2019 21:10:01 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", schema = "public")
public class Contact implements java.io.Serializable {

	private int id;
	private String name;
	private String contactfunction;
	private String email;
	private Integer phone;
	private Integer cellphone;
	private Set<Supplier> suppliers = new HashSet<Supplier>(0);

	public Contact() {
	}

	public Contact(int id) {
		this.id = id;
	}

	public Contact(int id, String name, String contactfunction, String email, Integer phone, Integer cellphone,
			Set<Supplier> suppliers) {
		this.id = id;
		this.name = name;
		this.contactfunction = contactfunction;
		this.email = email;
		this.phone = phone;
		this.cellphone = cellphone;
		this.suppliers = suppliers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "contactfunction", length = 100)
	public String getContactfunction() {
		return this.contactfunction;
	}

	public void setContactfunction(String contactfunction) {
		this.contactfunction = contactfunction;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Column(name = "cellphone")
	public Integer getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(Integer cellphone) {
		this.cellphone = cellphone;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "supplier_has_contact", schema = "public", joinColumns = {
			@JoinColumn(name = "contact_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "supplier_id", nullable = false, updatable = false) })
	public Set<Supplier> getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}

}
