package br.com.goinf.entities;
// Generated 13 de jan de 2019 21:10:01 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suppliertype generated by hbm2java
 */
@Entity
@Table(name = "suppliertype", schema = "public")
public class Suppliertype implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Supplier> suppliers = new HashSet<Supplier>(0);

	public Suppliertype() {
	}

	public Suppliertype(int id) {
		this.id = id;
	}

	public Suppliertype(int id, String name, Set<Supplier> suppliers) {
		this.id = id;
		this.name = name;
		this.suppliers = suppliers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suppliertype")
	public Set<Supplier> getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}

}
